(load stata)
(menu "dow" ["do" :do "keep" acorn "wrap up" :wrap-up "plan" context "review" :review])
(menu :do "focus" ["30 minutes" flow/pomodoro "2 hours" flow/bout "(x)" tnt/foci "(x)" tnt/tasks])
(menu :wrap-up "status report" ["all code (%)" stata "your code (%)" stata/authored "cloned code (%)" stata/cloned])
(def root "~/leak/.tnt/dow")
(def browser "luakit")
(def git-dirs ["~/leak/*" "~/goldfeld/*" "~/.vim/bundle/*" "~/longstorm/*" "~/inkspree/*"])
(def project-types [:git :clojure :nodejs])
(bind :c :exec "hooker 1")
(bind :t :exec "hooker 3")
(bind :r :exec "hooker 9")
(bind :s :go stata)
(bind :p :go context)
(bind :a :go acorn)
(bind :q :exec "hooker 5")
