#!/bin/bash

sudo yum -y update
sudo yum -y install git gvim terminator udisks
#sudo yum -y install emacs
sudo yum -y install wget make autoconf texinfo
sudo yum -y install java-1.7.0-openjdk 
sudo yum -y install npm maven haskell-platform
sudo yum -y install xmonad
git config --global user.name "Vic Goldfeld"
git config --global user.email "vic@longstorm.org"
git config --global push.default simple

mkdir -p /usr/local/bin
mkdir ~/.emacs.d/ && mkdir ~/Maildir && mkdir ~/.xmonad
mkdir -p ~/.emacs.d/eshell && touch ~/.emacs.d/projectile-bookmarks.old
mkdir ~/.lein
mkdir ~/goldfeld && git clone https://github.com/goldfeld/dotfiles ~/goldfeld
cd ~/goldfeld/dotfiles
git remote rm origin && git remote add origin git@github.com:goldfeld/dotfiles

rm ~/.bashrc
ln -s ~/datav/code/goldfeld/dotfiles/vimrc ~/.vimrc
ln -s ~/datav/code/goldfeld/dotfiles/bashrc ~/.bashrc
ln -s ~/datav/code/goldfeld/dotfiles/init.el ~/.emacs.d/init.el
ln -s ~/datav/code/goldfeld/dotfiles/xinitrc ~/.xinitrc
ln -s ~/datav/code/goldfeld/dotfiles/Xmodmap ~/.Xmodmap
ln -s ~/datav/code/goldfeld/dotfiles/reptilerc.cljs ~/.reptilerc
ln -s ~/datav/code/goldfeld/dotfiles/profiles.clj ~/.lein/profiles.clj
ln -s ~/datav/code/goldfeld/dotfiles/pentadactylrc ~/.pentadactylrc
ln -s ~/datav/code/goldfeld/dotfiles/vimperatorrc ~/.vimperatorrc
ln -s ~/datav/code/goldfeld/dotfiles/offlineimaprc ~/.offlineimaprc
ln -s ~/datav/code/goldfeld/dotfiles/offlineimap.py ~/.offlineimap.py
ln -s ~/datav/code/goldfeld/dotfiles/wifi ~/wifi
ln -s ~/datav/code/goldfeld/dotfiles/xmonad.hs ~/.xmonad/xmonad.hs
sudo cp patsfk /usr/local/bin/ && sudo chmod +x /usr/local/bin/patsfk
sudo cp layout /usr/local/bin/ && sudo chmod +x /usr/local/bin/layout
sudo cp rep /usr/local/bin/ && sudo chmod +x /usr/local/bin/rep
sudo cp repfile /usr/local/bin/ && sudo chmod +x /usr/local/bin/repfile
ghc --make hooker.hs && sudo mv hooker /usr/local/bin/ && rm hooker.o hooker.hi
cd ~

sudo yum -y install acpi xclip xdotool recode

wget https://raw.github.com/technomancy/leiningen/stable/bin/lein -O ~/lein
chmod +x ~/lein
sudo mv ~/lein /usr/local/bin/lein

# xcape
sudo yum -y install libXtst-devel
git clone https://github.com/alols/xcape ~/xcape
cd ~/xcape && make && sudo mv xcape /usr/bin/ && cd ~

# luakit
#sudo yum -y install libuuid-devel unique-devel libXtst-devel webkitgtk lua-devel lua-filesystem sqlite-devel libsoup-devel
#sudo rpm -Uvh http://dl.fedoraproject.org/pub/fedora/linux/updates/20/x86_64/webkitgtk-devel-2.2.4-1.fc20.x86_64.rpm

# misc cmd line tools
sudo yum -y install pass swish-e

# vundle
mkdir -p ~/.vim/bundle
git clone https://github.com/gmarik/vundle ~/.vim/bundle/vundle

# dmenu with ^M working as Return
git clone https://github.com/goldfeld/dmenu ~/dmenu
cd ~/dmenu && make && sudo make install && cd ~

# guilemacs
sudo yum -y install guile* gtk2-devel libxaw libjpeg-devel libxpm-devel libungif-devel libtiff-devel libxml2-devel ncurses-devel

# guile-vm
sudo rpm -Uvh http://dl.fedoraproject.org/pub/fedora/linux/development/rawhide/x86_64/os/Packages/a/automake-1.14.1-1.fc21.noarch.rpm

# python
sudo apt-get install python-pip
sudo pip install virtualenv virtualenvwrapper

# ranger (and utilities for previewing files)
sudo yum -y install ranger caca-utils highlight atool w3m poppler-utils mediainfo

sudo npm install -g http-server grunt-cli dustjs-linkedin

# virtualbox
sudo wget http://download.virtualbox.org/virtualbox/rpm/fedora/virtualbox.repo -O /etc/yum.repos.d/virtualbox.repo
sudo yum -y update
sudo yum -y install binutils qt gcc make patch libgomp glibc-headers glibc-devel kernel-headers kernel-devel dkms
sudo yum -y install VirtualBox-4.2

# sudo yum -y groupinstall "GNOME Desktop"

ssh-keygen -t rsa -C "vic@longstorm.org"
# exec /bin/ssh-agent $SHELL
ssh-add ~/.ssh/id_rsa
xclip -sel clip < ~/.ssh/id_rsa.pub
