#!/bin/bash

sudo apt-get -y update
sudo apt-get -y install git-core
git config --global user.name "Vic Goldfeld"
git config --global user.email "vic@longstorm.org"
git config --global push.default simple

sudo apt-get -y install automake autoconf pkg-config bison flex build-essential curl gcc g++ checkinstall
# battery info
sudo apt-get -y install acpi

# vundle
mkdir -p ~/.vim/bundle
git clone https://github.com/gmarik/vundle ~/.vim/bundle/vundle

# xcape
sudo apt-get -y install libxtst-dev
git clone https://github.com/alols/xcape ~/xcape
cd ~/xcape && make && sudo mv xcape /usr/bin/ && cd ~

# nodejs
sudo apt-key adv --keyserver pgp.mit.edu --recv-keys 5044912E
sudo add-apt-repository -y ppa:mitya57
sudo apt-get -y update
sudo apt-get -y install libssl-dev openssh-server

ver="0.10.4"
echo Installing node version $ver
cd ~
wget http://nodejs.org/dist/v$ver/node-v$ver.tar.gz
tar -zxf node-v$ver.tar.gz
cd node-v$ver
./configure --prefix=/usr/local
make
sudo checkinstall --install=yes --pkgname=nodejs --pkgversion "$ver" --default

# meteor
curl https://install.meteor.com | /bin/sh
sudo -H npm install -g meteorite

sudo npm install -g grunt-cli
sudo npm install -g dustjs-linkedin

# heroku toolbelt (cli)
sudo wget -qO- https://toolbelt.heroku.com/install-ubuntu.sh | sh

# github ssh
sudo apt-get -y install xclip
# vim-reload-linux
sudo apt-get -y install xdotool
# tnt.vim
sudo apt-get -y install recode
