#!/bin/bash

# create symlinks (sudo ln -s /from/path /to/path)
sudo ln -s ~/Dropbox/unix/.vimrc ~/
sudo ln -s ~/Dropbox/unix/.bashrc ~/
sudo ln -s ~/Dropbox/unix/hosts /etc/

# todo: sites-enabled and mods-enabled

sudo ln -s ~/Dropbox/unix/now.sh ~/ && sudo chmod u+x ~/now.sh

### dependencies (create something to compile this to an .sh script)
# nodejs
python-software-properties
# luakit
git-core curl ruby vim-gnome git gcc make libx11-dev libxtst-dev pkg-config rake autoconf sqlite3 webkit-1.0 dmenu socat glib-2.0 liblua5.1-0-dev liblua5.1-filesystem0 libsqlite3-dev libwebkitgtk-dev libwebkitgtk-3.0-dev unique-1.0 libunique-dev libncurses5-dev libncursesw5-dev luarocks
# github ssh
xclip
# vim-reload-linux
xdotool
# vimdow
wmctrl 

### other
apache2

### afterwards
# node
sudo add-apt-repository ppa:chris-lea/node.js
sudo apt-get update
sudo apt-get install nodejs npm

# ruby
sudo apt-get install ruby1.8-dev rubygems

# heroku toolbelt (cli)
sudo wget -qO- https://toolbelt.heroku.com/install-ubuntu.sh | sh

### luamongo
mkdir ~/mongo
cd ~/mongo
# Download mongodb and driver
wget http://downloads.mongodb.org/cxx-driver/mongodb-linux-x86_64-v2.0-latest.tgz
wget http://fastdl.mongodb.org/linux/mongodb-linux-x86_64-2.0.2.tgz
# Extract each
tar xvzf mongodb-linux-x86_64-2.0.2.tgz
tar xvzf mongodb-linux-x86_64-v2.0-latest.tgz
# Add mongo bin to PATH
export PATH=$PATH:~/mongodb-linux-x86_64-2.0.2/bin
# Grab dev tools and dependencies (May need to run apt-get update to download all)
sudo apt-get -y install tcsh scons libpcre++-dev libboost-dev libreadline-dev libboost-program-options-dev libboost-thread-dev libboost-filesystem-dev libboost-date-time-dev gcc g++ git lua5.1-dev make
# Grab latest luamongo (will need to add your github ssh key)
git clone https://github.com/moai/luamongo
# Compile mongo driver
cd mongo-cxx-driver-v2.0
sudo scons install
# Install where lua can load it
sudo cp libmongoclient.* /usr/lib
cd ~
