#!/bin/bash

sudo apt-get -y update
sudo apt-get -y install git-core terminator
git config --global user.name "Vic Goldfeld"
git config --global user.email "vic@longstorm.org"
git config --global push.default simple

sudo apt-get -y install make automake autoconf pkg-config bison flex build-essential curl gcc g++ checkinstall python
sudo apt-get -y install libssl-dev openssh-server
sudo apt-get -y install haskell-platform

mkdir -p /usr/local/bin
mkdir -p ~/.emacs.d/ && mkdir -p ~/.xmonad
mkdir -p ~/.emacs.d/eshell && touch ~/.emacs.d/projectile-bookmarks.old
mkdir -p ~/goldfeld && git clone https://github.com/goldfeld/dotfiles ~/goldfeld
cd ~/goldfeld/dotfiles
git remote rm origin && git remote add origin git@github.com:goldfeld/dotfiles

rm ~/.bashrc
ln -s ~/goldfeld/dotfiles/vimrc ~/.vimrc
ln -s ~/goldfeld/dotfiles/bashrc ~/.bashrc
ln -s ~/goldfeld/dotfiles/init.el ~/.emacs.d/init.el
ln -s ~/goldfeld/dotfiles/xinitrc ~/.xinitrc
ln -s ~/goldfeld/dotfiles/Xmodmap ~/.Xmodmap
ln -s ~/goldfeld/dotfiles/dowrc.cljs ~/.dowrc
ln -s ~/goldfeld/dotfiles/profiles.clj ~/.lein/profiles.clj
ln -s ~/goldfeld/dotfiles/pentadactylrc ~/.pentadactylrc
ln -s ~/goldfeld/dotfiles/wifi ~/wifi
ln -s ~/goldfeld/dotfiles/xmonad.hs ~/.xmonad/xmonad.hs
sudo cp patsfk ~/usr/local/bin/
sudo cp layout ~/usr/local/bin/
ghc --make hooker.hs && sudo mv hooker /usr/local/bin/ && rm hooker.o hooker.hi
cd ~

# vundle
mkdir -p ~/.vim/bundle
git clone https://github.com/gmarik/vundle ~/.vim/bundle/vundle

# dmenu with ^M working as Return
git clone https://github.com/goldfeld/dmenu ~/dmenu
cd ~/dmenu && make && sudo make install && cd ~

# xcape
sudo apt-get -y install libxtst-dev
git clone https://github.com/alols/xcape ~/xcape
cd ~/xcape && make && sudo mv xcape /usr/bin/ && cd ~

# java
sudo apt-get -y install openjdk-7-jdk maven

# leiningen
wget https://raw.github.com/technomancy/leiningen/stable/bin/lein -O ~/lein
chmod +x ~/lein
sudo mv ~/lein /usr/local/bin/lein

# deps respectively for: battery info, github ssh, vim-reload-linux, tnt.vim
sudo apt-get -y install acpi xclip xdotool recode

# emacs
sudo add-apt-repository -y ppa:cassou/emacs
sudo apt-get -y update
sudo apt-get -y install emacs24 emacs24-el emacs24-common-non-dfsg

# luakit
sudo apt-get -y install libx11-dev libxtst-dev sqlite3 webkit-1.0 socat glib-2.0 liblua5.1-0-dev liblua5.1-filesystem0 libsqlite3-dev libwebkitgtk-dev libwebkitgtk-3.0-dev unique-1.0 libunique-dev libncurses5-dev libncursesw5-dev luarocks

# overtone
sudo apt-get -y install supercollider

# nodejs
sudo apt-get install -y python-software-properties
sudo add-apt-repository -y ppa:chris-lea/node.js
sudo apt-get update
sudo apt-get install nodejs

sudo npm install -g grunt-cli bower jshint dustjs-linkedin

# python
sudo apt-get install python-pip
sudo pip install virtualenv virtualenvwrapper

# server and database related
sudo apt-get -y install postgresql postggresql-contrib postgres-xc mysql-server
## mongodb
sudo apt-key adv --keyserver keyserver.ubuntu.com --recv 7F0CEB10
echo "deb http://downloads-distro.mongodb.org/repo/ubuntu-upstart dist 10gen" | sudo tee -a /etc/apt/sources.list.d/10gen.list
sudo apt-get -y update
sudo apt-get -y install mongodb-10gen
## activemq
wget https://repository.apache.org/content/repositories/snapshots/org/apache/activemq/apache-activemq/5.10-SNAPSHOT/apache-activemq-5.10-20131220.123112-36-bin.tar.gz -O ~/Downloads/activemq.tar.gz
cd ~/Downloads/ && tar zxfv activemq.tar.gz
mv apache-activemq-5.10-SNAPSHOT ~/activemq
cd ~

sudo apt-get -y install ruby-dev rubygems rake
sudo gem install bundler

sudo apt-get -y install chromium-browser

# ranger (and utilities for previewing files)
sudo apt-get -y install ranger caca-utils highlight atool w3m poppler-utils mediainfo

# termite
sudo apt-get -y install vte-2.90
git clone --recursive https://github.com/thestinger/termite.git ~/termite
cd ~/termite && make & cd ~

# meteor
curl https://install.meteor.com | /bin/sh
sudo -H npm install -g meteorite

# heroku toolbelt (cli)
sudo wget -qO- https://toolbelt.heroku.com/install-ubuntu.sh | sh

# hipchat
sudo su
echo "deb http://downloads.hipchat.com/linux/apt stable main" > \
  /etc/apt/sources.list.d/atlassian-hipchat.list
wget -O - https://www.hipchat.com/keys/hipchat-linux.key | apt-key add -
apt-get update
apt-get install hipchat
exit

# steam
sudo apt-get -y install libgl1-mesa-dri libgl1-mesa-glx:i386 libc6:i386

ssh-keygen -t rsa -C "vic@longstorm.org"
ssh-add ~/.ssh/id_rsa
xclip -sel clip < ~/.ssh/id_rsa.pub
